language: ruby
rvm:
  - "2.3.1"
services:
  - postgresql
test:
  adapter: postgresql
  database: blog_test
before_script:
  - psql -c 'create database blog_test;' -U postgres
script: bundle exec rails t
