# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9b84e7ed9a5cedf093650c19f82d546b76dd80354501f5c650dc78c369860f3351b9e4ae89060482429f35fcbf0945b366f42d83d888807afd8f22bd84dd69

test:
  secret_key_base: 212c2263e585def84518e110ca46ba36ee45b58528c43d221c2a13a6832d501df37c4f586f7338bc99d11e2ee4d518d5cdce826c46a49f44df6caf278582069e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
